### PR TITLE
Initial import

### PR DESCRIPTION
**Pull request by havardholvik**
Initial import of existing web component, plus test scripts and a dev environment.

Tested like:

1. `yarn test` - Runs the basic unit tests written
2. `yarn build` - Builds two versions of the lib; one cjs version for use with a bundler, and one iife version for direct loading using a script tag
3. `yarn dev` - Run storybook, which includes stories for testing out the web component

Todo:
- [x]  License
- [x]  Port old build routine from `dev-docs`
- [x]  Npm publish script + dist files
- [x]  Some integration tests?
- [x] Add remaining params to storybook 

Screenshot 2022-06-24 at 14 18 09

### CODE REVIEW

**Comment by martrik** [comment]
Love to see it 🤩 I think both the project structure and the exectuion is great. Nice idea to have a storybook we can use to test, the only question is what room URL to use I guess 🤔

**Comment by havardholvik** [comment]
> Love to see it 🤩 I think both the project structure and the exectuion is great. Nice idea to have a storybook we can use to test, the only question is what room URL to use I guess 🤔 

Yea, that is the question. Either Ill make it a regular param in the story, or allow something like `yarn dev <roomname>`

**Comment by martrik** [comment]
Lovely!

**Comment by yuriypavlyshak** [comment]
Worked well for me, I was able to run a storybook via `STORYBOOK_ROOM=<roomUrl> yarn dev`, setting different parameters works as well (apart from the ones that aren't added yet).

Would it be possible to have a way to trigger commands e.g. `toggleCamera()` from storybook as well?

**Review by remi-quinto — APPROVED** [review]
Worked pretty well for me as well, and quite easy to test. 

I'm curious about the `emptyRoomInvitation` parameter. I see in [this notion doc](https://www.notion.so/whereby/Preferences-and-release-flags-ce31f8a5adee43508baaaeea4c7eaf81) that it allows to hide the "copy this url to add people" but I noticed no change in practice.

**Pull request merged**
