### PR TITLE
Bundle rtcstats

### PR DESCRIPTION
**Pull request by thyal**
Add rtcstats to bundle

### CODE REVIEW

**Review by kevinwhereby — APPROVED** [review]
tested working in the usual suspects

I still see rtcstats in my yalc.lock though... guess we have to publish to really find out
```
"@whereby/jslib-media@whereby/jslib-media.git#1.4.1":
  version "1.4.1"
  resolved "https://codeload.github.com/whereby/jslib-media/tar.gz/abc55b7e2d3af9c71cb3f3a2953291bb79725064"
  dependencies:
    events "^3.3.0"
    mediasoup-client "3.6.100"
    rtcstats "github:whereby/rtcstats#v5.3.0"
    sdp "^2.2.0"
    sdp-transform "^2.14.1"
    socket.io-client "4.7.2"
    uuid "^9.0.1"
    webrtc-adapter "^7.3.0"

"rtcstats@github:whereby/rtcstats#v5.3.0":
  version "5.3.0"
  resolved "https://codeload.github.com/whereby/rtcstats/tar.gz/f696794035acc18a0d42229217a9a3b7630d524e"
  
  ```

**Review by havardholvik — APPROVED** [review]

**Comment by kevinwhereby** [comment]
definitely bundling it though:
image

**Comment by thyal** [comment]
> tested working in the usual suspects
> 
> I still see rtcstats in my yalc.lock though... guess we have to publish to really find out

Yeah, not sure. It should be bundling it. Let's publish and try

**Comment by havardholvik** [comment]
> > tested working in the usual suspects
> > I still see rtcstats in my yalc.lock though... guess we have to publish to really find out
> 
> Yeah, not sure. It should be bundling it. Let's publish and try

This is expected. One could argue that at this point rtcstats is a devDependency, but lets not worry about this now 👍

**Pull request merged**
